import { observable, makeObservable, action } from "mobx";
import { Post, EPostStatus } from "../models/Post";
import { User } from "../models";
import { PAGE_SIZE_DEFAULT } from "../config";

export class HomeStore {
    @observable post: Post[] = [];
    @observable size: number = PAGE_SIZE_DEFAULT || 10;
    @observable page: number = 0;
    @observable totalPage: number = 10;
    

    constructor() {
        makeObservable(this);
    }

    @action init() {
            this.post = [new Post({
                _id: '1',
                title: 'Cần bán VESPA đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '2',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }),
            new Post({
                _id: '3',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }),
            new Post({
                _id: '4',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '5',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '6',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '7',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '8',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '9',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '10',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '11',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '12',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '13',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '14',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '15',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '16',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '17',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '18',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '19',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }), new Post({
                _id: '20',
                title: 'Cần bán Áo đời mới',
                description: 'Vespa Sprint S 150 đã từng sản xuất nhưng không phải động cơ Iget, động cơ mới này đang được đáp ứng tốt về độ bền, giảm tiêu hao nhiên liệu rất đáng kể so với trước. Thiết kế của dòng Sprint S 150cc giống hoàn toàn với dòng Sprint 125cc, trang bị đầy đủ tất cả công nghệ mới nhất từ dòng Sprint S 125 hiện tại. Sự khác biệt chính là khối động cơ 150cc.',
                createdBy: new User(),
                created_at: new Date(),
                expires: new Date(),
                view: 9999999999999999999999999999999999999999999,
                status: EPostStatus.PENDING,
                images: [],
            }),
        ]
    }
}